# goal: Move the tool (e.g. camera)
#       to the given pose
geometry_msgs/Pose target_pose 
---
# result
geometry_msgs/Pose end_pose
---
# feedback: none! We want to limit robot traffic.
# Get feedback from robot_arm topics
#geometry_msgs/Pose current_pose
